#deprecated
app_home:
  path: /
  controller: App\Controller\DefaultController::default

#deprecated
app_index:
  path: /index
  controller: App\Controller\DefaultController::index

default:
  path: /
  controller: App\Controller\DefaultController::default

default_index:
  path: /index
  controller: App\Controller\DefaultController::index

app_restricted:
  path: /restricted
  controller: App\Controller\HomeController::home # splash screen

app_info:
  path: /info
  controller: App\Controller\HomeController::info

app_contact:
  path: /contact
  controller: App\Controller\InboxController::contact

app_inbox:
  path: /inbox
  controller: App\Controller\InboxController::inbox

app_cart:
  path: /cart
  controller: App\Controller\CartController::cart

admin:
  path: /admin
  controller: App\Controller\Admin\AdminDashboardController::admin

admin_inbox:
  path: /admin/inbox
  controller: App\Controller\Admin\AdminDashboardController::inbox

app_features:
  path: /features
  controller: App\Controller\TopicController::index
